= Code can be an art 행사 참석 후기
정상혁
2007-06-01
:jbake-type: post
:jbake-status: published
:jbake-tags: 행사후기
:jabke-rootpath: /
:rootpath: /
:content.rootpath: /
:idprefix:

지난 2007/05/19(토)에  http://www.creativecommons.or.kr/[CCK(Creative Commons Korea)]에서 주최한  http://ccsalon.tistory.com/[ccSalon] 행사가 있었습니다 . 이날의 행사 제목은 'Code can be an art'였었죠

관련 글과 같이 올릴려고 하다 보니 거의 2주가 지나서야 후기를 쓰게 되네요.

* 관련 글
** http://blog.benelog.net/1230429[QB로 만든 Code can be an art 출력]
** http://blog.benelog.net/1230312[코드와 예술]

저는 이 행사를 http://www.goodhyun.com/[김국헌님의 블로그]에서 알게되어 혼자 행사장을 찾아갔었습니다. 제가 워낙 길치라서 노트북에다 약도를 저장해서 띄워놓고 화면을 계속 보고 갔는데도  힘들게 행사장을 찾아갔습니다. -_- 길에서 걷는 중에 노트북을 펴놓고 화면과 주위를 번갈아 가는 모습을 이상하게 본 사람도 있었을 것 같습니다.^^;

주요 행사 내용 중에 다음과 같은 내용들이 인상깊었었습니다.

=== DJ성우님의 발표

개발자와 DJ의 공통점으로 '밤늦게 컴퓨터 앞에서 작업하는 일이 많다','이미 있는 것으로부터 새로운 창조물을 만든다' 등을 드신 것이 기억납니다. 그리고 개발자들도 DJ들처럼 공동작업 그룹 같은것을 자발적으로 결성해서 활동하면 어떨까 하는 제안도 신선하게 들렸습니다.

* 미디어 아티스트  http://beingmedia.tistory.com/entry/%EC%9E%85%EC%9E%90%EC%9D%B8%EC%83%9DNet[최승준]님의 발표

최승준 님의 '입자인생'(http://beingmedia.tistory.com/entry/%EC%9E%85%EC%9E%90%EC%9D%B8%EC%83%9DNet[http://beingmedia.tistory.com/entry/입자인생Net] )이라는 작품은 예술적이면서 철학적인 설명을 해주셔서 심오하게 까지 느껴졌습니다. 그런 것 프로그래밍 할려면 물리학이나 수학도 많이 알아야 될 것 같다고 생각하니 저런 작품들은 여러 분야들의 종합성과물이라는 생각이 들었습니다.


=== http://reagan.egloos.com/226206[황리건]님의 발표
황리건님의 작품 중에는 맨 마지막 것이 가장 기억에 남습니다. 화면에 보이는 선의 한 부분을 클릭하면 거기서 원이 추가 되고 선분은 나누어져서 새로운 움직임을 보여주는 프로그램이였습니다. 이 작품을 꼭 보여주시고 싶어 하시면서, 이 것을 한달동안 힘들게 만드셨다고 말씀하시는데, 창작자로써의 뿌듯함이 느껴지시는 것 같았습니다. 요즘은 고객이 만들라고만 한 프로그램만 만들고 있는 저로서는 부러웠어요 ^^;

=== 코드잼
http://blog.benelog.net/1230429[QB로 만든 Code can be an art 출력] 글에서 썼듯이 코드만 짜가고 발표는 못했습니다. 그래도 기획하신 분의 의도, 발표하신 분들의 기분은 알 수 있을 것 같았습니다.

=== 패널토론  8Bit 키드의 생애
80년대 초반 컴퓨터를 처음 시작한 세대들의 추억담이였습니다. 저보다는 앞세대의 분들이였고 사용한 기계와 환경은 달랐지만, 그런 이야기를 하시면서 어떤 기분이 드실지는 왠지 알 것 같았습니다. 아마 제가 '허큘리스'라는 말만 들어도  느껴지는 기분과 비슷하지 않을까요? ^^;

=== 패널토론  예술로서의 코드
타이틀이 맞는지 모르겠군요. 김창준님이 귀여니의 시구를 인용하시던 부분에서 웃지 않을수 없었습니다. 앞의 다른 순서들이 '코드로 만든 결과물인 예술', '만든다는 것의 기쁨'에 초점이 맞춰진 것이라면 이 순서는 '코드 자체로써의 예술'에 중심을 둔 것 같습니다.

모든 순서가 끝난 뒤에 뒤풀이가 있었습니다. 저는 아는 사람도 없고 해서 분위기가 어색하지 않을까 걱정을 했었는데, 저녁 식사 때부터 같은 테이블에 앉았던 자원봉사자 분들이 재밌는 자리를 만들어주셔서 편하게 술자리를 할 수 있었습니다 ^^; 그리고 개인적으로 평소 애독하는 블로그의 주인이신 류한석님, 김국헌님을 가까이서 뵐 수 있어서 영광이였습니다~ ^^ 같은 테이블에 앉았던  대학생 분은 그 두분께  블로그 내용이 인쇄된 종이에다가 사인을 해달라고  부탁하더군요.

보통 저는 술자리에 참석하면 끝까지 남거나 쓰러지거나 둘 중에 하나였었는데, 이날은 아내가 근처까지 데리러 오는 바람에 먼저 일어날수 밖에 없어서 무척 아쉬웠습니다.

다음 모임때부터는 저도 자원봉사자로 참여하겠다고 했는데 빨리 그 때가 왔으면 좋겠네요~
