= 스프링 프레임웍의 최근 소식들 모음 등
정상혁
2008-12-10
:jbake-type: post
:jbake-status: published
:jbake-tags: Spring,뉴스
:jabke-rootpath: /
:rootpath: /
:content.rootpath: /
:idprefix:

* http://javajigi.tistory.com/207[Spring Source 진영의 향후 RoadMap]
* http://www.ksug.org/77[SpringSource의 또 다른 야심작, tc Server]
* http://www.ksug.org/72["Spring Python" 파이썬 개발자에게도 봄(?)을]
* http://www.ksug.org/68[Spring, Grails를 품에 안다]
* http://www.ksug.org/79[Spring One America 2008 참석기 링크 모음]
* http://blog.springsource.com/2008/12/05/spring-framework-30-m1-released/[First Spring Framework 3.0 milestone released]http://whiteship.me/2091[]
** http://whiteship.me/2091[스프링 프레임워크 3.0 M1 배포~]

역시 최근 들어 스프링소스의 발걸음이 더욱 빨라졌습니다. Grails, Spring Python, tc Server, 3.0M1 발표.. 현란하게 소식이 쏟아지는군요. 그만큼 공부할 것도 더 늘겠지만, 그래도 반갑고 기대감을 가지게 하는 소식들입니다.

대규모 투자를 받고, 일을 더 벌이고 하면서 스프링소스가 돈맛에 초심을 잃을까봐 걱정을 하시는 분도 많이 계시는 듯 합니다. 그래도 성공적인 사업 구조가 정착되어서 그 수익이 개발자들에게 도움이 되는 제품들을 더 잘 개발하는데 쓰인다면야 굳이 돈을 많이 벌게 되는 것이 나쁘다고는 생각하지 않습니다. 유료로 제공되는 제품이 많아진다고 해도, 그럴만한 가치가 있는 제품이면 돈을 내고, 그것이 아니라도 프레임웍이나 서버, 개발도구의 시장은 독점 시장이 아니니 다른 선택을 할 수 있는 대안이 많을 것입니다. 물론 지금까지의 스프링의 행보를 봐서는 충분히 앞으로도 가치있는 결과물을 만들 것이라고 기대하고 있습니다.

여러 소식들 중에 솔직히 가장 재미있었던 것은, Spring one America 2008에 참석하신 분들을 통해 알게된, 로드존슨의 나이였습니다. 스프링 핵심 개발자인 유겐할러의 말에 의하면 로드존슨은 38살 정도라고 하네요.

왜 저는 로드존슨을 당연히 40대라고 생각했을까.. 하고 분석해보니, Expert one-on-one J2EE Design and Developement 책 때문에 그런 선입관을 가지게 된 것 같습니다.

이 책이 나온 것이 2003년인데, 그렇다면 이 때는 33살이였단 말이되는군요.
이 책을 쓰는데도 2년 정도가 걸렸다고 들은 것 같습니다.
그리고 책 표지에 보면 로드존슨은 음악학(Musicology)에 박사학위가 있다는 말도 있습니다. 그래서, 다른 분야도 박사까지 하고 컴퓨터 분야에서도 이정도 경지까지 가려면 적어도 이 책 출판시에 30대 중후반은 되지 않았을까.. 하는 추측을 한 것이죠.

