= Ubuntu 24.04 설치
정상혁
2025-10-09
:jbake-type: post
:jbake-status: published
:jbake-tags: linux
:idprefix:

새 컴퓨터를 받아서 설치한 프로그램들을 정리해봅니다.

* Ubuntu는 영문판으로 설치
** `Desktop`, `Download` 같은 디렉토리가 영문으로 나오는 것이 편리해서

== 한글 설정
`sudo apt install ibus-hangul`

`Settings` 에서

* `Regision & Language` 에서 `Manage Installed Lanauges` 에 'Korean' 추가
* `Keyboard` > `Input Sources` 에 `Korean(Hangul)` 추가하고 "..." 눌러서 `Preference` 선택
** `Hangul toggle key` 에 `Shift + Space` 지정

== 하드웨어 설정

=== 키보드 설정
일부 키보드의 경우 F1~F12가 잘 인식되지 않은 경우도 있음. 해당 장비가 애플 키보드 타입으로 인식되고 자동 모드가 Fn가 기본적으로 눌러져있는 것으로 인식되기 떄문. hid_apple 모듈의 fnmode 변수 설정으로 이 문제를 해결할 수 있음.

* 현재 모드 확인 : `lsmod | grep hid_` (디폴트는 자동 모드인 3)
* 보통 2로 모드 설정을 하면 잘 되고, 그래도 안되면 disable인 3으로
* 일시적으로 설정 값이 변경하여 테스트 : `echo 2 | sudo tee /sys/module/hid_apple/parameters/fnmode`

[source]
.키보드 펑션키 모드 변경이 재부팅 후에도 적용되도록
----
echo "options hid_apple fnmode=2" | sudo tee /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u
----

참고자료

* https://sunyzero.tistory.com/290
* https://mathncode.tistory.com/25

=== 웹 캠 설정
Intel Ultra 7 258v CPU를 쓰는 Dell XPS 13 plus 9350에서는 웹캠을 위한 드라이버 설치를 따로 해줘야했음.
같은 CPU를 쓰는 Lenovo Thinkpad X1 Carbon G13는 기본 설치만으로 잘 되었음.

Dell XPS 13 plus 9350에서 웹캠이 안 잡힐 때 참고한 자료

* https://wiki.ubuntu.com/IntelMIPICamera
* https://wiki.ubuntu.com/Dell

== CLI 도구

=== Terminator
여러 창을 띄우기에 편한 터미널 프로그램

`sudo apt install terminator`

=== curl

`sudo apt install curl`

=== ifconfig

`sudo apt install net-tools`

==== ssh 설정

`sudo vi /etc/ssh/ssh_config` 하여 아래를 마지막에 추가

[source]
----
HostkeyAlgorithms ssh-dss,ssh-rsa
KexAlgorithms +diffie-hellman-group1-sha1
----

https://kr.analysisman.com/2018/08/linux-ssh.html 참조

=== git / gitk

`sudo apt-get install git gitk`

=== GitHub SSH 설정

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

=== oh-myzsh

[source]
----
sudo apt install zsh
curl -L http://install.ohmyz.sh | sh
----

( https://github.com/robbyrussell/oh-my-zsh 참고 )

terminator의 `Preference` > `Profile` > `Command` 에서

* `Run a custom command instead of my shell` 체크
* `Custom commands` : `zsh`

=== scm_breeze
zsh에서 실행할 때의 기준

[source]
----
git clone https://github.com/scmbreeze/scm_breeze.git ~/.scm_breeze
~/.scm_breeze/install.sh
source "${ZDOTDIR:-$HOME}/.zshrc
bash
source ~/.bashrc
exit
----

( https://github.com/ndbroadbent/scm_breeze 참고 )

== 개발 환경

여러 JDK를 설치하고 관리하는 방법은 SDKMAN + direnv를 추천 ( https://blog.benelog.net/installing-jdk.html 참조)

=== SDKMAN

[source]
----
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk install java
----

https://sdkman.io/install 참조

=== direnv

* `sudo apt install direnv` 설치
* `~/.bashrc` 와 `~/.zshrc` 에 `eval "$(direnv hook bash)"` 추가

https://direnv.net/docs/hook.html 참조

=== IntelliJ

[source]
----
sudo apt install fuse
----

https://www.jetbrains.com/ko-kr/toolbox-app/ 에서 Toolbox로 설치

* Terminal에서 zsh 지정
** `Settings` > `Tools` > `Application Settings` > `Shell Path` : `/bin/zsh`
* Plugin 설치
** https://plugins.jetbrains.com/plugin/7391-asciidoc
** https://plugins.jetbrains.com/plugin/1065-checkstyle-idea

=== Node.js

==== nvm 설치

[source]
----
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
----


.~/.bash_profile, ~/.zshrc, ~/.profile,  ~/.bashrc 등에 추가

[source]
----
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
----

https://github.com/nvm-sh/nvm#installing-and-updating 참고

== 정보 관리 프로그램

=== 크롬

[source]
----
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
----

=== Obsidian

snap으로 설치하면 한글 문제가 있음. Appimage로 설치

=== Pinta

`snap install pinta`

=== VidCutter

`snap install vidcutter`

https://github.com/ozmartian/vidcutter 참조

=== ShotCut

`snap install shotcut --classic`

https://shotcut.org/ 참조

== 기타 참고
이전 버전에서 참고한 자료

=== 무선 인터넷 안 잡힐 때

* `rfkill list all`
* http://askubuntu.com/questions/380586/wireless-is-disabled-by-hardware-switch-wifi-doesnt-work-hard-blocked-yes
* http://askubuntu.com/questions/847250/new-ubuntu-16-04-with-no-wifi/847282

=== NGINX 설치 후 자동으로 시작 안하게

`sudo update-rc.d -f nginx disable`

=== Secure Boot

https://wiki.ubuntu.com/UEFI/SecureBoot 참조
