= Jürgenized: Spring 리드 개발자의 이름에서 나온 코드 품질 용어
정상혁
2026-08-29
:jbake-type: post
:jbake-status: published
:jbake-tags: spring, code-review, refactoring
:description: Spring 커뮤니티에는 기여한 코드가 리드 개발자 Juergen Hoeller의 손을 거쳐 품질이 완성된다는 뜻의 'Jürgenized'라는 용어가 있습니다. 이 용어의 정의와 유래, PR을 직접 커밋으로 반영하는 Juergen Hoeller의 작업 방식, Rod Johnson이 인터뷰에서 밝힌 그의 생산성을 정리합니다.
:toc:
:idprefix:

2019년에 한국 스프링 사용자 모임 페이스북 그룹에 spring-framework 저장소에 PR을 올린 경험담이 공유된 적이 있습니다. 그 글에 달린 첫 댓글은 "유게나이즈 당하셨군요. 축하드립니다"였습니다. 뭔가를 당했는데 축하를 받는 묘한 상황이었습니다. 저도 그 대화에 댓글로 참여하면서 관련 자료를 찾아봤는데, 'Jürgenized'라는 용어의 유래와 실제 사례가 흥미로워서 글로 정리합니다.

== '유게나이즈 당하셨군요'라는 축하 댓글

발단이 된 사연은 이렇습니다. 글을 올린 분은 Kotlin으로 개발하다가 DB 같은 리소스를 닫는 시점에 발생한 exception이 Spring의 bean destroy 로직에서 잡혀서 ``info`` 레벨로만 기록되는 상황을 겪었습니다. ``org.springframework``의 로그 레벨을 ``ERROR``로 설정해 두었기에 그 로그를 보지 못했고, 원인을 파악한 뒤 해당 로그를 더 높은 레벨로 남겨달라는 link:https://github.com/spring-projects/spring-framework/pull/23200[PR #23200]을 올렸습니다.

이 PR에 Spring Framework의 리드 개발자인 Juergen Hoeller가 직접 답을 달았고, 그 소식을 커뮤니티에 공유하자 "유게나이즈 당하셨군요"라는 축하 댓글이 달린 것입니다. 이어진 댓글에서 한 분은 이 용어를 아래와 같이 풀이했습니다.

____
그냥 보면 괜찮아 보이는 이슈나 코드가 유겐이 등장하면 전에 미처 보지 못했던 관점에서 새롭게 문제 제기가 되면서, 최종적으로는 품질이 뛰어난 코드로 변모하게 되는 현상
____

== Oliver Drotbohm이 기록한 Jürgenization의 정의

Spring Data 프로젝트를 이끌었던 Oliver Drotbohm은 2013년에 link:https://odrotbohm.de/2013/03/juergenized/[Jürgenized]라는 글에서 이 용어를 사전 항목 형식으로 정의했습니다. footnote:[이 글은 원래 olivergierke.de에 올라왔습니다. 저자가 결혼 후 Oliver Gierke에서 Oliver Drotbohm으로 이름을 바꾸면서 블로그 주소도 바뀌었고, 옛 주소는 새 주소로 리다이렉트됩니다.] 번역하면 아래와 같습니다.

____
Jürgenization (명사)

당장의 문제를 푸는 데는 충분해 보이는 코드를, 견고하고 품질이 보증되며 완벽하게 문서화되고 확장 가능한 코드로 바꾸는 과정. 이 과정은 원래 코드의 전면 재작성(Karma level 0)부터 사소한 수정(Karma level 10)까지 다양한데, 보통 코드 작성자가 이 과정을 얼마나 자주 통과해 봤는지에 따라 달라진다.
____

이 글은 용어의 유래도 밝힙니다. Spring Framework에 들어올 기여 코드를 다루는 Juergen Hoeller의 방식에서 나온 말로, 코드를 core codebase에 넣으려면 코드와 그 작성자가 함께 jürgenized 되어야 한다는 것입니다. 글이 쓰인 시점에는 Spring 생태계 프로젝트 전반의 코드 품질 보증 과정을 가리키는 말로 의미가 넓어져 있었습니다.

== Spring Project Infrastructure 발표와 Refactor Type 분류

저는 이 단어를 SpringSource의 Gunnar Hillert와 Roy Clarkson이 2013년에 발표한 link:https://www.slideshare.net/royclarkson/spring-project-infrastructure[Spring Project Infrastructure]라는 슬라이드에서 처음 봤습니다. Spring 프로젝트들이 GitHub로 이전하고 PR로 기여를 받는 과정을 소개하는 발표인데, 후반부에 'Jürgenization'이라는 슬라이드가 등장합니다. 같은 제목의 link:https://www.youtube.com/watch?v=m74QsK5XCeQ[발표 영상]에서는 이를 Juergen Hoeller의 코딩 스타일과 기준에 맞는 코드 품질과 엄격함이라고 설명합니다.

이 용어를 리팩터링의 한 유형으로 분류한 문서도 있습니다. link:http://notes.experimental-software.com/SoftwareEngineering/Programming/Refactoring.html[Refactoring 정리 노트]는 Refactor Type을 TDD, Boy Scout Rule, Comprehension, Preparatory, Planned, Long term으로 나열하는데, 그 목록의 마지막 항목이 Jürgenizing입니다. 출처로는 앞서 소개한 Oliver Drotbohm의 글을 링크하고 있습니다.

== 머지 대신 직접 커밋: PR #23200의 처리 과정

spring-framework 저장소의 link:https://github.com/spring-projects/spring-framework/pulls[PR 목록]을 보면 Stéphane Nicoll 같은 커미터는 올라온 PR을 그대로 merge해 주는 경우가 많습니다. 반면 Juergen Hoeller는 PR을 리뷰하고 참고하되, 반영은 본인의 커밋으로 직접 하는 방식을 선호하는 듯합니다.

앞의 PR #23200도 그렇게 처리됐습니다. 흐름을 따라가 보면 Jürgenization의 축소판을 볼 수 있습니다.

. 제안자가 bean destroy 실패 로그를 ``info``에서 더 높은 레벨로 올려달라는 PR을 올렸습니다.
. Juergen Hoeller가 리뷰하면서 새로운 관점을 제시했습니다. 이 로그는 Spring 5.0/4.3에서는 ``warn`` 레벨이었는데 5.1에서 로그 레벨 정책을 정비하다가 생긴 회귀라는 점을 짚었고, 제안대로 ``error``까지 올리는 방안에는 bean destroy 실패가 여러 단계로 이뤄지는 소멸 과정의 부분적인 실패일 뿐이므로 불필요한 노이즈를 만든다며 선을 그었습니다.
. 결론은 PR의 merge가 아니었습니다. Juergen Hoeller가 직접 작성한 link:https://github.com/spring-projects/spring-framework/commit/56cc0d02e9[커밋]이 "Bean destruction exceptions consistently logged at warn level"이라는 메시지와 함께 반영됐고, PR은 이 커밋의 "Closes gh-23200"으로 닫혔습니다.

제안한 사람의 문제의식은 받아들이되, 원인 분석과 최종 코드는 자신의 기준으로 다시 만들어내는 과정이 그대로 드러납니다.

== Rod Johnson이 꼽은 가장 생산적인 프로그래머

Juergen Hoeller의 이런 위상을 보여주는 인터뷰가 있습니다. Ed Burns가 쓴 link:https://www.goodreads.com/book/show/227849.Secrets_of_the_Rock_Star_Programmers[Secrets of the Rock Star Programmers](2008, 번역서 제목은 '세상을 뒤흔든 프로그래머들의 비밀')에 실린 Rod Johnson 인터뷰입니다. 제 기억에 따르면, 함께 일했던 프로그래머 가운데 가장 생산적이었던 사람이 누구냐는 질문에 Rod Johnson은 생각할 것도 없이 Juergen Hoeller라고 답합니다. 이어서 Juergen Hoeller가 개발 속도와 품질 모든 면에서 가장 뛰어난 결과를 보이며, 자신이라면 여러 번의 시행착오를 거쳤을 문제를 그는 한 번에 해결할 것이라고 말합니다. footnote:[번역서를 기억에 의존해 옮긴 것이라 정확한 표현은 책과 다를 수 있습니다.]

20년 가까이 지난 인터뷰인데, Juergen Hoeller는 지금도 Spring Framework의 리드로 활동하고 있습니다. 2024년에는 Spring Framework 1.0 릴리스 20주년을 맞아 Rod Johnson과 함께 link:https://spring.io/blog/2024/04/18/a-bootiful-podcast-spring-founders-rod-johnson-and-juergen-hoeller-on-the/[팟캐스트]에 출연했고, link:https://www.youtube.com/watch?v=i_fiHmg1qM0[Spring I/O 2025의 발표 무대]에도 함께 섰습니다. 한 프레임워크를 20년 넘게 같은 기준으로 지켜온 셈이니, 'Jürgenized'라는 용어도 당분간 유효할 듯합니다.

== 참고 자료

* https://www.facebook.com/groups/springkorea/permalink/2056700451108240/[한국 스프링 사용자 모임의 원글과 댓글]
* https://odrotbohm.de/2013/03/juergenized/[Oliver Drotbohm - Jürgenized]
* https://www.slideshare.net/royclarkson/spring-project-infrastructure[Spring Project Infrastructure 슬라이드]
* https://www.youtube.com/watch?v=m74QsK5XCeQ[Spring Project Infrastructure 발표 영상]
* http://notes.experimental-software.com/SoftwareEngineering/Programming/Refactoring.html[Refactoring - notes.experimental-software.com]
* https://github.com/spring-projects/spring-framework/issues/23199[spring-framework issue #23199]
* https://github.com/spring-projects/spring-framework/pull/23200[spring-framework PR #23200]
* https://github.com/spring-projects/spring-framework/commit/56cc0d02e9[Juergen Hoeller의 반영 커밋]
* https://www.goodreads.com/book/show/227849.Secrets_of_the_Rock_Star_Programmers[Secrets of the Rock Star Programmers]

'''

이 포스트는 Claude Code와 정상혁이 함께 작성했습니다.
